Wire front backend
opensim-org/opensim-viewer pull request #65
Opened 2023-06-23 17:12 UTC by aymanhab

This includes the changes to back end side only, specifically:
- add functions to support retrieval of models by id 
- urls to support retrieval of specific models
- models are uploaded kept in folders rather than as individual files to leave place for original moedels/data/meta-data files

>

2023-07-05 16:25 UTC, aymanhab commented
@AlbertoCasasOrtiz for your review

2023-07-05 18:58 UTC, AlbertoCasasOrtiz requested changes
LGTM! Only some minor comments. 

Also, It was complaining about axios not found (I think in CI, Jest is complaining about the same). I just had to manually install axios (`npm install axios`) on my computer and it worked.

2023-07-13 20:03 UTC, AlbertoCasasOrtiz commented
Hi @aymanhab, I just noticed I didn't told you I reviewed this. The error in jest is because axios is not being automatically installed.

2023-07-27 19:01 UTC, AlbertoCasasOrtiz commented
Since it was a while since I reviewed this, I run it locally after manually adding a model to the database and it worked perfectly without having to install anything.

2023-07-27 21:05 UTC, aymanhab commented on src/backend/backend/backend/models.py
>  class Model(models.Model):
yes, good idea. Should we hold this PR for it or wait?

2023-07-27 21:06 UTC, aymanhab commented
Now that I merged the PR that fixes the backend, not sure if this is ready or not, can you comment @AlbertoCasasOrtiz ? Thank you

2023-07-31 16:58 UTC, aymanhab commented
@AlbertoCasasOrtiz can you comment on the status of this PR? Thank you

2023-07-31 19:55 UTC, AlbertoCasasOrtiz commented
Hi @aymanhab. There were some conflicts and errors here, but I think I have solved everything. Everything should be working as expected now.

2023-07-31 20:07 UTC, aymanhab commented
Perfect, thanks so much @AlbertoCasasOrtiz

2023-08-01 18:24 UTC, AlbertoCasasOrtiz commented on src/components/pages/OpenSimScene.tsx
> +          'http://localhost:8000/models/viz/default/',
Solved by adding the [] to the useEffect.

2023-08-01 18:25 UTC, AlbertoCasasOrtiz approved these changes

2023-08-01 18:25 UTC, AlbertoCasasOrtiz commented
@aymanhab I just noticed I forgot to approve this PR. I just did it.

2023-08-01 19:06 UTC, aymanhab commented on src/components/pages/OpenSimScene.tsx
> +          'http://localhost:8000/models/viz/default/',
👍

2023-08-01 19:07 UTC, merged