Drag and drop trc mot and c3d files
opensim-org/opensim-viewer pull request #79
Opened 2023-08-25 18:54 UTC by aymanhab

Backend is needed only once to login

2023-08-25 19:58 UTC, aymanhab commented
For your review @AlbertoCasasOrtiz

2023-08-28 18:20 UTC, AlbertoCasasOrtiz requested changes
Everything seems to works, except for a .mot file from my opencap data (maybe the error is in the file and not in the converter?)

2023-08-28 18:48 UTC, aymanhab commented on src/backend/backend/backend/osimConverters/convertMotForce2Gltf.py
Thanks, I took a look and noticed that the file has no ground-reaction-forces.. Note that not any mot is supported as of now, since there's no underlying model, only mot files that contain ground reaction forces are supported for now. Would you be able to test with a mot file that contain GRFs? Thank you

2023-08-29 18:09 UTC, aymanhab commented
Thanks much

2023-08-29 18:09 UTC, merged